M48
; DRILL file {KiCad 7.0.1-0} date 2023 May 08, Monday 01:12:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-08T01:12:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X106.75Y-70.685
X106.75Y-76.465
T2
X103.25Y-53.25
X103.25Y-93.9
X146.75Y-53.25
X146.75Y-93.9
T0
M30
